# Generated by Django 2.0.5 on 2018-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180920_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title_h3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_p',
            field=models.TextField(),
        ),
    ]
