# Generated by Django 2.0.5 on 2018-09-27 09:02

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0003_payinfoorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payinfoorder',
            name='id',
        ),
        migrations.AddField(
            model_name='payinfoorder',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
