# Generated by Django 2.0.5 on 2018-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0004_auto_20180927_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfoorder',
            name='istype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
